name:                 BootstrapValidator
highlighter:          pygments
#highlighter:          rouge
relative_permalinks:  false

source:               .
destination:          _gh_pages
markdown:             kramdown
#markdown:             redcarpet
exclude:              ['node_modules', '*.less']
url:                  http://bootstrapvalidator.com/
paginate:             5
permalink:            /news/:title/
timezone:             Asia/Ho_Chi_Minh

# Custom variables
# not defined by Jekyll
current_version:      0.5.0
released_date:        2014-07-14
github_watchers:      568
github_forks:         225
github_downloads:     32200
twitter_followers:    121
download:
  dist:               https://github.com/nghuuphuoc/bootstrapvalidator/releases/download/v0.5.0/bootstrapvalidator-dist-0.5.0.zip
  tag:                https://github.com/nghuuphuoc/bootstrapvalidator/archive/v0.5.0.zip
repository:
  source:             https://github.com/nghuuphuoc/bootstrapvalidator
  docs:               https://github.com/nghuuphuoc/bootstrapvalidator/gh-pages
  docs_edit:          https://github.com/nghuuphuoc/bootstrapvalidator/edit/gh-pages
ga_code:              UA-44786951-2
jquery_plugin_url:    http://plugins.jquery.com/bootstrapValidator
disqus:               bootstrapvalidator